using System.Text;
using System.Text.RegularExpressions;
using ProgramMigrationAnalyzer.Core;

namespace ProgramMigrationAnalyzer.Translation;

public sealed partial class MigrationSourceTranslator : ISourceTranslator
{
    public bool CanTranslate(SourceLanguage language) =>
        language is SourceLanguage.CSharp or SourceLanguage.Informix4Gl;

    public Task<TranslationResult> TranslateAsync(
        AnalysisResult analysis,
        MigrationTargetFramework targetFramework,
        CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var generated = analysis.Language switch
        {
            SourceLanguage.CSharp => ModernizeCSharp(analysis, targetFramework),
            SourceLanguage.Informix4Gl => Translate4Gl(analysis, targetFramework, cancellationToken),
            _ => throw new NotSupportedException("The selected source language cannot be translated.")
        };

        var result = new TranslationResult
        {
            Source = analysis.Source,
            TargetFramework = targetFramework,
            GeneratedCode = generated
        };

        if (analysis.Language == SourceLanguage.Informix4Gl)
        {
            result.Warnings.Add("Generated scaffold requires manual type, transaction, UI, and SQL verification.");
        }

        return Task.FromResult(result);
    }

    private static string ModernizeCSharp(
        AnalysisResult analysis,
        MigrationTargetFramework targetFramework)
    {
        var builder = new StringBuilder();
        builder.AppendLine($"// Migration Target: {FormatTarget(targetFramework)}");
        builder.AppendLine("// Generated by Program Migration Analyzer");
        builder.AppendLine("// Review every migration comment before using this code in production.");
        builder.AppendLine();

        foreach (var line in analysis.Source.Content.ReplaceLineEndings("\n").Split('\n'))
        {
            if (line.Contains("ConfigurationManager", StringComparison.Ordinal))
            {
                builder.AppendLine("// TODO(Migration): Inject IConfiguration instead of ConfigurationManager.");
            }

            if (line.Contains("HttpWebRequest", StringComparison.Ordinal) ||
                line.Contains("WebRequest", StringComparison.Ordinal))
            {
                builder.AppendLine("// TODO(Migration): Replace legacy request code with an injected HttpClient and async APIs.");
            }

            if (line.Contains("BinaryFormatter", StringComparison.Ordinal))
            {
                builder.AppendLine("// TODO(Migration): SECURITY - select a safe serialization format. Do not port BinaryFormatter.");
            }

            if (line.Contains("SqlConnection", StringComparison.Ordinal) ||
                line.Contains("SqlCommand", StringComparison.Ordinal))
            {
                builder.AppendLine("// TODO(Migration): Move direct ADO.NET access behind a repository boundary.");
            }

            builder.AppendLine(line);
        }

        return builder.ToString();
    }

    private static string Translate4Gl(
        AnalysisResult analysis,
        MigrationTargetFramework targetFramework,
        CancellationToken cancellationToken)
    {
        var className = ToIdentifier(Path.GetFileNameWithoutExtension(analysis.Source.FileName)) + "Service";
        var builder = new StringBuilder();
        builder.AppendLine($"// Migration Target: {FormatTarget(targetFramework)}");
        builder.AppendLine("// Generated by Program Migration Analyzer");
        builder.AppendLine("// This scaffold preserves detected structure and intent. Manual verification is required.");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Threading;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine();
        builder.AppendLine("namespace ProgramMigrationAnalyzer.Generated;");
        builder.AppendLine();
        builder.AppendLine($"public sealed class {className}");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly ILegacyRepository _repository;");
        builder.AppendLine();
        builder.AppendLine($"    public {className}(ILegacyRepository repository)");
        builder.AppendLine("    {");
        builder.AppendLine("        _repository = repository;");
        builder.AppendLine("    }");

        foreach (var function in analysis.Functions)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var methodName = function.Kind == "Main" ? "RunAsync" : ToPascalCase(function.Name);
            var parameters = string.Join(", ", function.Parameters.Select(parameter =>
                $"{InferType(parameter.Name)} {ToCamelCase(parameter.Name)}"));
            var returnType = function.Kind == "Main"
                ? "Task"
                : InferReturnType(function);

            builder.AppendLine();
            builder.AppendLine($"    public {returnType} {methodName}({parameters})");
            builder.AppendLine("    {");
            builder.AppendLine($"        // Source lines: {function.StartLine}-{function.EndLine}");
            builder.AppendLine("        // TODO(Migration): Verify original 4GL types and business behavior.");

            foreach (var call in function.CalledFunctions)
            {
                builder.AppendLine($"        // Calls legacy routine: {call}");
            }

            foreach (var table in function.ReferencedTables)
            {
                builder.AppendLine($"        // Uses table: {table}");
            }

            if (function.Kind == "Main")
            {
                builder.AppendLine("        return Task.CompletedTask;");
            }
            else if (returnType == "decimal")
            {
                var price = function.Parameters.FirstOrDefault(parameter => parameter.Name.Contains("price", StringComparison.OrdinalIgnoreCase))?.Name;
                var quantity = function.Parameters.FirstOrDefault(parameter =>
                    parameter.Name.Contains("qty", StringComparison.OrdinalIgnoreCase) ||
                    parameter.Name.Contains("quantity", StringComparison.OrdinalIgnoreCase))?.Name;
                if (price is not null && quantity is not null)
                {
                    builder.AppendLine($"        return {ToCamelCase(price)} * {ToCamelCase(quantity)};");
                }
                else
                {
                    builder.AppendLine("        return 0m;");
                }
            }
            else
            {
                builder.AppendLine("        return null;");
            }

            builder.AppendLine("    }");
        }

        if (analysis.SqlStatements.Count > 0)
        {
            builder.AppendLine();
            builder.AppendLine("    // Detected SQL requiring repository migration:");
            foreach (var sql in analysis.SqlStatements)
            {
                builder.AppendLine($"    // [{sql.CommandType}] {sql.RawSql.ReplaceLineEndings(" ")}");
            }
        }

        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("public interface ILegacyRepository");
        builder.AppendLine("{");
        builder.AppendLine("    // TODO(Migration): Replace raw SQL with parameterized Dapper, EF Core, or a dedicated data adapter.");
        builder.AppendLine("    Task<int> ExecuteAsync(string sql, CancellationToken cancellationToken = default);");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string InferReturnType(FunctionInfo function)
    {
        if (function.Name.Contains("total", StringComparison.OrdinalIgnoreCase) ||
            function.Name.Contains("calc", StringComparison.OrdinalIgnoreCase))
        {
            return "decimal";
        }

        return "object?";
    }

    private static string InferType(string name)
    {
        if (name.Contains("qty", StringComparison.OrdinalIgnoreCase) ||
            name.Contains("count", StringComparison.OrdinalIgnoreCase) ||
            name.EndsWith("id", StringComparison.OrdinalIgnoreCase))
        {
            return "int";
        }

        if (name.Contains("price", StringComparison.OrdinalIgnoreCase) ||
            name.Contains("amount", StringComparison.OrdinalIgnoreCase) ||
            name.Contains("total", StringComparison.OrdinalIgnoreCase))
        {
            return "decimal";
        }

        if (name.Contains("date", StringComparison.OrdinalIgnoreCase))
        {
            return "DateTime";
        }

        return "object?";
    }

    private static string FormatTarget(MigrationTargetFramework target) =>
        target == MigrationTargetFramework.Net8 ? ".NET 8" : ".NET 10";

    private static string ToIdentifier(string value)
    {
        var cleaned = InvalidIdentifierCharacters().Replace(value, "_");
        if (string.IsNullOrWhiteSpace(cleaned))
        {
            return "MigratedProgram";
        }

        return char.IsDigit(cleaned[0]) ? "_" + cleaned : cleaned;
    }

    private static string ToPascalCase(string value)
    {
        var parts = WordSeparators().Split(value).Where(part => part.Length > 0);
        var converted = string.Concat(parts.Select(part => char.ToUpperInvariant(part[0]) + part[1..]));
        return ToIdentifier(string.IsNullOrWhiteSpace(converted) ? "MigratedFunction" : converted);
    }

    private static string ToCamelCase(string value)
    {
        var pascal = ToPascalCase(value);
        return char.ToLowerInvariant(pascal[0]) + pascal[1..];
    }

    [GeneratedRegex(@"[^A-Za-z0-9_]")]
    private static partial Regex InvalidIdentifierCharacters();

    [GeneratedRegex(@"[_\-\s]+")]
    private static partial Regex WordSeparators();
}
